SystemOrganization addCategory: #Petrich2!
SystemOrganization addCategory: #'Petrich2-Core'!
SystemOrganization addCategory: #'Petrich2-DUI'!
SystemOrganization addCategory: #'Petrich2-InstructionSelector'!
SystemOrganization addCategory: #'Petrich2-Parsing'!
SystemOrganization addCategory: #'Petrich2-Pig'!
SystemOrganization addCategory: #'Petrich2-Tests'!
SystemOrganization addCategory: #'Petrich2-XBeeConversion'!
